### ISSUE TITLE
Unable to compile rklotz on Windows

### ISSUE THREAD

**Issue by JanSichula** [vgarvardt/rklotz#14]
Hello,

I like your project and it is being considered as a basis for our new church web site. Since there seems to be an issue with Glide tool on Windows (see https://github.com/Masterminds/glide/issues/51) I have converted the package references to us Godep. It all seems promising but when I try to build, I end with following error:

c:\Inetpub\GoLanguage\src\github.com\vgarvardt\rklotz_godep>go build
# github.com/vgarvardt/rklotz_godep/cfg
C:\Inetpub\GoLanguage\src\github.com\vgarvardt\rklotz_godep\cfg\middleware.go:17: cannot convert nil to type bool
C:\Inetpub\GoLanguage\src\github.com\vgarvardt\rklotz_godep\cfg\middleware.go:20: cannot use templateDataError (type bool) as type error in argument to getContext:
        bool does not implement error (missing Error method) 

Any advice on to successfully compile your exciting project on my Win 8.1 Pro X64 dev box will be greatly appreciated.

I am using Go 1.4.2.

**Comment by vgarvardt** [comment]
I did not make fixed versions vendoring for Glide - I think this is the problem. Right now I'm experimenting with gb as build and vendoring tool and like it a lot. Will convert this project to gb - this should solve the problem. Will handle this during the week.

**Comment by JanSichula** [comment]
@vgarvardt Hello and thank you for your prompt response. The GB tool sounds promising and powerful, I shall have a look at it myself as it might come handy for future projects. In the meantime, may your effort to modify your project bring a good fruit in reasonable time.  

P. S. It looks like so many GoLang people are on the Linux or Mac boxes that they do not remember a minority of us on Windows. :-)

**Comment by JanSichula** [comment]
@vgarvardt In the mean time https://github.com/Masterminds/glide was updated to version 0.5.0 with support for Windows but requiring GoLang 1.5. Now one way or another, I will probably have to get Rklotz to play well with GoDeps as otherwise it will be impossible to publish your project on an Open Shift PaaS which supports BoltDB unlike Heroku or Bluemix.

**Comment by JanSichula** [comment]
@vgarvardt I have been toying a lot today with OpenShift Online platform and it is now a sure fact that it only accepts vendored dependencies that are compiled after the code is pushed to an OpenShift Git repository. So far whenever I have produced a working build of any app on my machine in tandem with GoDep, it then also worked on OpenShift. So the most promising way forward will be to get rklotz playing nice with GoDep.

**Comment by vgarvardt** [comment]
Migrated project to gb and fixed issue that you got - the problem was in outdated code for pongo2 support. Now `make vendor && make build` (that actually invokes `gb vendor update -all` and `gb build`]) builds project with fixed dependencies versions, so this should never happen again.
